version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - knappador
  ignore:
  - dependency-name: vulkano-shaders
    versions:
    - 0.20.0
    - 0.21.0
  - dependency-name: vulkano
    versions:
    - 0.20.0
    - 0.21.0
  - dependency-name: vulkano-win
    versions:
    - 0.20.0
    - 0.21.0
  - dependency-name: image
    versions:
    - 0.23.12
    - 0.23.13
  - dependency-name: rustfft
    versions:
    - 5.0.1
  - dependency-name: env_logger
    versions:
    - 0.8.2
