use_small_heuristics = "Max"
brace_style = "PreferSameLine"
fn_single_line = true
where_single_line = true
use_field_init_shorthand = true
overflow_delimited_expr = true
match_block_trailing_comma = true
license_template_path = "./licensing/lgpl3-header.txt"
